
[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.3"
cairo-sys-rs = "0.2.0"
libc = "0.1"

[dependencies.atk-sys]
path = "../atk-sys"
version = "0.2.0"

[dependencies.gdk-pixbuf-sys]
path = "../gdk-pixbuf-sys"
version = "0.2.0"

[dependencies.gdk-sys]
path = "../gdk-sys"
version = "0.2.0"

[dependencies.gio-sys]
path = "../gio-sys"
version = "0.2.0"

[dependencies.glib-sys]
path = "../glib-sys"
version = "0.2.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "0.2.0"

[dependencies.pango-sys]
path = "../pango-sys"
version = "0.2.0"

[lib]
name = "gtk_sys"

[package]
build = "build.rs"
links = "gtk"
name = "gtk-sys"
version = "0.2.0"
