language: rust
rust:
  - nightly
  - stable
env:
  - GTK=3.4
  - GTK=latest
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - rm -rf gtk-sys
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b crate https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./git_deps.sh cairo glib gdk gtk pango
  - ./build.sh
