
[build-dependencies]
pkg-config = "^0.3.5"

[dependencies]
bitflags = "^0.3"
libc = "^0.1"

[dependencies.glib-sys]
path = "../glib-sys"
version = "^0.2.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "^0.2.0"

[lib]
name = "atk_sys"

[package]
build = "build.rs"
description = "FFI bindings to atk"
documentation = "http://gtk-rs.org/docs/atk_sys"
homepage = "http://gtk-rs.org/"
keywords = ["atk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "atk"
name = "atk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.2.0"
