
[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.3"
libc = "0.1"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"

[dependencies.gdk-pixbuf-sys]
path = "../gdk-pixbuf-sys"
version = "0.2.0"

[dependencies.gio-sys]
path = "../gio-sys"
version = "0.2.0"

[dependencies.glib-sys]
path = "../glib-sys"
version = "0.2.0"

[dependencies.gobject-sys]
path = "../gobject-sys"
version = "0.2.0"

[dependencies.pango-sys]
path = "../pango-sys"
version = "0.2.0"

[lib]
name = "gdk_sys"

[package]
build = "build.rs"
description = "FFI bindings to gdk"
documentation = "http://gtk-rs.org/docs/gdk_sys"
homepage = "http://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk"
name = "gdk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.2.0"
