[build-dependencies]
pkg-config = "0.3.5"

[dependencies]
bitflags = "0.3"
cairo-sys-rs = "0.2.1"
libc = "0.1"
glib-sys = "0.2.1"
gobject-sys = "0.2.1"
gio-sys = "0.2.1"
gdk-pixbuf-sys = "0.2.1"
pango-sys = "0.2.1"

[lib]
name = "gdk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to gdk"
documentation = "http://gtk-rs.org/docs/gdk_sys"
homepage = "http://gtk-rs.org/"
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gdk"
name = "gdk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.2.1"
